/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary-red': '#EB1B1A',
        'red-header': '#F01C1B',
        'primary-white': '#E2E2E2',
        'primary-green': '#55B718',
        'primary-gray': '#444444',
        'primary-black': '#1C1C1C',
      },
      fontFamily: {
        'Troika': ['Troika', 'sans-serif'],
        'Cattedrale': ['Cattedrale', 'sans-serif'],
        'Cydre': ['Cydre', 'sans-serif'],
      },
      boxShadow: {},
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        }
      },
      animation: {
        fadeIn: 'fadeIn 0.5s ease-out forwards',
      }
    },
    screens: {},
  },
  plugins: [],
  safelist: [
    'text-[1.25vw]',
    'text-[1.67vw]',
    'py-[0.36vw]',
    'px-[1.25vw]',
    'rounded-[0.31vw]',
    'gap-[0.83vw]',
    'mt-[1.88vw]',
    'w-[50vw]',
    'ml-[2vw]',
    'bg-primary-gray',
    'uppercase',
    'font-Troika',
    'font-Cydre',
    'font-Cattedrale',
    'text-primary-white',
    'text-primary-green',
    'text-primary-red',
    'bg-primary-black',
    'bg-primary-gray',
    'bg-primary-green',
    'bg-primary-red',
    'rounded-[0.21vw]',
    'text-[0.73vw]',
    'hover:scale-105',
    'transition-transform',
    'duration-300',
    'ease-in-out',
    'cursor-pointer',
    'z-10',
    'z-50',
    'flex',
    'flex-row',
    'flex-col',
    'flex-wrap',
    'justify-start',
    'items-start',
    'items-center',
    'relative',
    'group',
    'animate-fadeIn',
    'whitespace-nowrap',
  ],
};
